FROM alpine:3.20
ARG TARGETARCH
LABEL org.opencontainers.image.title="xbn plus ++" \
      org.opencontainers.image.source="https://github.com/kele812/xbn-plus-plus" \
      org.opencontainers.image.licenses="MPL-2.0"
RUN apk add --no-cache ca-certificates tzdata && mkdir -p /etc/XboardNode-Plus
COPY --chmod=755 dist/xboard-node-linux-${TARGETARCH} /usr/local/bin/xboard-node
WORKDIR /etc/XboardNode-Plus
ENTRYPOINT ["xboard-node"]
CMD ["-c", "/etc/XboardNode-Plus/config.yml"]
